[package]
name = "ciclo"
description = "Exhaustive cycle enumeration."
version = "0.1.0"
edition = "2021"
license = "MIT"
license_file = "LICENSE"
homepage = "https://github.com/metamolecular/ciclo"
readme = "README.md"

[dependencies]

[dev-dependencies]
pretty_assertions = "1.3.0"
